Models/ErrorViewModel.cs
namespace Operación_en_bolsa.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Operación_en_bolsa.Models
{
    public class Usuario
    {
        public string? Nombre {get;set;}
        public string? Apellido {get;set;}
        public string? Email {get;set;}
        [DataType(DataType.Date)]
        public DateTime? Fecha {get;set;}
        public List<string> Instrumentos {get;set;}=new List<string>{"S&P", "Down Jones","Bonos US"};
        public List<string> InstrumentosSeleccionados {get;set;}=new List<string>();
        public decimal Monto{get;set;}
        
        public decimal CalcularInversion(){
            return Monto/(decimal)InstrumentosSeleccionados.Count()*1.0m; 
        }
        public decimal CalcularIGV(){
            return CalcularInversion()*0.18m;
        }
        public decimal CalcularMonto(){
            return CalcularInversion()+CalcularIGV();
        }
        public decimal CalcularComision(){
            decimal comision;
            if(this.Monto>300)comision=1;
            else comision=3;
            return comision;
        }
         public double CalcularMontoTotal(){
           return (double)(CalcularComision()+CalcularMonto()*(decimal)InstrumentosSeleccionados.Count());
        }
        
    }
}

Controllers/BolsaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Operación_en_bolsa.Models;

namespace Operación_en_bolsa.Controllers
{
    public class BolsaController : Controller
    {
        
        private readonly ILogger<BolsaController> _logger;

        public BolsaController(ILogger<BolsaController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            Usuario u=new Usuario();
            Console.WriteLine("Controlador ejecutado");
            return View(u);

        }
        [HttpPost]
        public IActionResult Registro(Usuario user)
        {
            
            if (user.InstrumentosSeleccionados == null || !user.InstrumentosSeleccionados.Any())
            {   
                ModelState.AddModelError("InstrumentosSeleccionados", "Por favor seleccione al menos una opción");
                Index();
            }else{
                Console.WriteLine("Controlador ejecutado 2");
                List<string>select=user.InstrumentosSeleccionados;
                ViewData["usuario"]=user;
                ViewData["lista"]=select;
                Usuario u=new Usuario();
                return View("Index",u);
            }
            Usuario us=new Usuario();
            return View("Index",us);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Operación_en_bolsa.Models;

namespace Operación_en_bolsa.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Bolsa/Index.cshtml
@model Operación_en_bolsa.Models.Usuario;
@{
    ViewBag.Title="Registrar Inversión";
    var lista=ViewData["lista"]as List<string>;
    var user=ViewData["usuario"]as Usuario;
}
<div class="container">
    <h1 align="center">@ViewData["Title"]</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-controller="Bolsa" asp-action="Registro" method="post">
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label">Nombre:</label>
                    <input asp-for="Nombre" class="form-control"/>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="Apellido" class="control-label">Apellido:</label>
                    <input asp-for="Apellido" class="form-control"/>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="Email" class="control-label">Correo  Electronico:</label>
                    <input asp-for="Email" class="form-control"/>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="Fecha" class="control-label">Fecha:</label>
                    <input asp-for="Fecha" class="form-control"/>
                </div>
                <br>
                <div class="form-group">
                    <label class="control-label">Intrumentos:</label>
                    <br>
                    @foreach (var item in Model.Instrumentos)
                    {
                        <div>
                            <input type="checkbox" name="InstrumentosSeleccionados" value="@item" id="@item" @(Model.InstrumentosSeleccionados.Contains(item) ? "checked" : "") />
                            <label for="@item">@item</label>
                        </div>
                    }
                     <span asp-validation-for="InstrumentosSeleccionados" class="text-danger"></span>
                </div>
                <br>
                <div class="form-group">
                    <label asp-for="Monto" class="control-label">Monto a invertir:</label>
                    <input asp-for="Monto" type="number" required class="form-control"/>
                </div>
                <br>
                <button type="submit">Invertir</button>
            </form>
        </div>
    </div>
    <br>
    <div  class="row justify-content-center">
        @if(lista!=null){
            <table class="table table-striped table-bordered table-haver">
                <thead>
                    <tr>
                        <th>Instrumento</th>
                        <th>Inversión</th>
                        <th>Fecha</th>
                        <th>IGV</th>
                        <th>Monto</th>
                    </tr>
                </thead>
                @if(lista!=null){
                    <tbody>
                        @foreach(string c in lista){
                            <tr>
                                <td>@c</td>
                                <td>@user.CalcularInversion()</td>
                                <td>@user.Fecha</td>
                                <td>@user.CalcularIGV()</td>
                                <td>@user.CalcularMonto()</td>
                            </tr>
                        }
                    </tbody>
                }
            </table>
        }
        
        @if(user!=null){
            <div>
                <h3>La comisión es de: @user.CalcularComision()$</h3>
                <h3>El Monto total a pagar es de: @user.CalcularMontoTotal()$</h3>
        
            </div>
        }
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Operar en la bolsa";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <button>
        <a asp-controller="Bolsa" asp-action="Index">OPERAR</a>
    </button>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Operación_en_bolsa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Operación_en_bolsa.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Operación_en_bolsa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bolsa" asp-action="Index">Opere En Bolsa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bolsa" asp-action="Index">Acerca</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Operación_en_bolsa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>